philippines_django_postgis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('regions.urls')),
    path('admin/', admin.site.urls),
]

regions/urls.py
from django.urls import path
from regions.views import RegionDetailView, RegionListView, IndexView

urlpatterns = [
    path('RegionDetailView/<int:pk>', RegionDetailView.as_view(), name='region-detail-view'),
    path('RegionListView/', RegionListView.as_view(), name='region-list'),
    path('', IndexView.as_view(), name='index'),
]

regions/models.py
from django.db import models
from django.contrib.gis.db import models as geomodels


class Region(models.Model):
    adm1alt1en = models.CharField(max_length=100, blank=False)
    wkb_geometry = geomodels.MultiPolygonField()

    class Meta:
        verbose_name_plural = 'regions'
        # order of drop-down list items
        ordering = ('adm1alt1en',)

regions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.views.generic import DetailView, ListView, CreateView, TemplateView
from regions.models import Region


class RegionDetailView(DetailView):
    template_name = 'region-detail.html'
    model = Region


class RegionListView(ListView):
    model = Region
    template_name = 'region-search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        result = Region.objects.filter(Q(adm1alt1en=query))
        return result


class IndexView(TemplateView):
    template_name = 'region-search.html'

templates/base.html
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Region</title>
</head>
<body>
{%  include 'navbar.html' %}
{% block body_content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'region-list' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'region-list' %}">
      <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>

</nav>

templates/region-search.html
{% extends 'base.html' %}
{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}
{% block body_content %}
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.2.0/leaflet-omnivore.min.js'></script>

 <div class="container">
     {% leaflet_map "main" callback="map_init"%}
  </div>



<br>



<script type="text/javascript">
    function map_init(map, options) {
            // zoom to point
        {% for  region in region_list %}
          console.log("{{region.wkb_geometry}}");
          console.log("////");
          console.log(omnivore.wkt.parse('{{ region.wkb_geometry}}'));
          let region_multipolygon = omnivore.wkt.parse('{{ region.wkb_geometry}}');
          region_multipolygon.addTo(map);
          map.fitBounds(region_multipolygon.getBounds());
        {% endfor %}

    }

</script>

    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">id num</th>
            <th scope="col">region</th>
        </tr>
        </thead>
        <tbody>
        {% for  region in region_list %}
            <tr>
                <td>{{ region.id }}</td>
                <td><a href="{% url 'region-detail-view' pk=region.pk %}">{{ region.adm1alt1en }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}